export const FETCH_MOVIES = 'fetch_movies_from_api'
export const FETCH_MOVIE_DETAILS = 'fetch_movie_details_from_api'
export const OPEN_MODAL = 'open_modal'
export const SEARCH = 'search'
export const HAS_MORE = 'has_more'
